services:
    # сервис основного приложения
    app:
        build: .
        image: country-directory
        env_file:
            - .env
        volumes:
            - ./src:/src
            - ./media:/media
            - ./logs:/logs
            - ./docs:/docs
        working_dir: /src/
        command: python main.py

    # сервис для выполнения периодического задания
    cron:
        build: .
        image: country-directory-cron
        env_file:
            - .env
        volumes:
            - ./src:/src
            - ./media:/media
            - ./logs:/logs
            - ./cron:/cron
        entrypoint: sh /cron/crontab.sh
